import test from 'node:test';import assert from 'node:assert/strict';
import {SystemOneClient,Semaphore} from '../src/client.mjs';
import {mockSystemOne,envelope} from './helpers.mjs';
const q={yes:{type:'noul',instructions:'Is it blue?'}};
async function fixture(t,handler){const s=await mockSystemOne(handler);t.after(()=>s.close());return s;}
test('Exact Kev endpoint and body, optional auth and model override',async t=>{const s=await fixture(t),client=new SystemOneClient({url:s.url,apiKey:'local-key'});await client.ask({color:'blue'},q,{model:'local-custom'});const r=s.requests[0];assert.equal(r.url,'/v1/systemone');assert.equal(r.headers.authorization,'Bearer local-key');assert.equal(r.body.model,'local-custom');assert.deepEqual(Object.keys(r.body).sort(),['model','questions','state']);});
test('No TypeSafe authorization is needed for local server',async t=>{const s=await fixture(t);await new SystemOneClient({url:s.url}).ask('text',q);assert.equal(s.requests[0].headers.authorization,undefined);});
test('Models uses Kev models[] not OpenAI data[]',async t=>{const s=await fixture(t);const r=await new SystemOneClient({url:s.url}).models();assert.equal(r.models[0].id,'kev-latest');});
for(const status of [301,302,400,401,403,404,422,429,500,503])test(`HTTP ${status} fails safely without body/secret leakage`,async t=>{const s=await fixture(t,({res})=>{res.writeHead(status,{'content-type':'application/json',location:'http://example.com'});res.end('{"secret":"DO_NOT_ECHO"}');});await assert.rejects(new SystemOneClient({url:s.url}).ask('text',q),e=>e.code==='http_error'&&!e.message.includes('DO_NOT_ECHO'));assert.equal(s.requests.length,1);});
test('Bounded retry only on explicitly transient status',async t=>{const s=await fixture(t,({res,index})=>{if(index===1){res.writeHead(503);res.end();}else return false;});const c=new SystemOneClient({url:s.url,retries:1});await c.ask('text',q);assert.equal(s.requests.length,2);assert.equal(c.metrics.retries,1);});
for(const [name,handler]of [
 ['HTML',({res})=>{res.writeHead(200,{'content-type':'text/html'});res.end('<b>no</b>');}],
 ['invalid JSON',({res})=>{res.writeHead(200,{'content-type':'application/json'});res.end('oops');}],
 ['empty body',({res})=>{res.writeHead(200,{'content-type':'application/json'});res.end();}],
 ['missing answers',({res})=>{res.writeHead(200,{'content-type':'application/json'});res.end('{}');}],
 ['invalid UTF8',({res})=>{res.writeHead(200,{'content-type':'application/json'});res.end(Buffer.from([0xff,0xfe]));}],
])test(`Reject response ${name}`,async t=>{const s=await fixture(t,handler);await assert.rejects(new SystemOneClient({url:s.url}).ask('s',q),e=>e.code==='invalid_response');});
test('Request budget checked before sending',async t=>{const s=await fixture(t);await assert.rejects(new SystemOneClient({url:s.url,maxRequestBytes:128}).ask('x'.repeat(200),q),e=>e.code==='request_too_large');assert.equal(s.requests.length,0);});
for(const lengthHeader of [true,false])test(`Response bytes bounded (length header ${lengthHeader})`,async t=>{const s=await fixture(t,({res})=>{res.writeHead(200,{'content-type':'application/json',...(lengthHeader?{'content-length':10000}:{})});res.end('x'.repeat(10000));});await assert.rejects(new SystemOneClient({url:s.url,maxResponseBytes:128}).ask('s',q),e=>e.code==='response_too_large');});
test('Timeout bounds incomplete streaming body',async t=>{const s=await fixture(t,({res})=>{res.writeHead(200,{'content-type':'application/json'});res.write('{');});const start=Date.now();await assert.rejects(new SystemOneClient({url:s.url,timeoutMs:60}).ask('s',q),e=>e.code==='timeout');assert.ok(Date.now()-start<2000);});
test('Caller cancellation aborts active request',async t=>{const s=await fixture(t,()=>{}),c=new AbortController(),p=new SystemOneClient({url:s.url}).ask('s',q,{signal:c.signal});setTimeout(()=>c.abort(new Error('cancelled by test')),20);await assert.rejects(p,/cancelled/);});
test('Queue and active request limits prevent unbounded fanout',async t=>{const s=await fixture(t,async({res,body})=>{await new Promise(r=>setTimeout(r,25));res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify(envelope(body.questions)));});const c=new SystemOneClient({url:s.url,maxConcurrent:2,maxQueue:2}),results=await Promise.allSettled(Array.from({length:12},()=>c.ask('s',q)));assert.equal(results.filter(r=>r.status==='fulfilled').length,4);assert.ok(s.maxActive<=2);assert.equal(c.semaphore.active,0);});
test('Aborted semaphore waiters are removed',async()=>{const sem=new Semaphore(1,2),release=await sem.acquire(),c=new AbortController(),wait=sem.acquire(c.signal);c.abort();await assert.rejects(wait);assert.equal(sem.queue.length,0);release();assert.equal(sem.active,0);});
test('Circuit opens after failures and recovers after cooldown',async t=>{let healthy=false,time=100;const s=await fixture(t,({res})=>{if(healthy)return false;res.writeHead(503);res.end();});const c=new SystemOneClient({url:s.url,breakerFailures:2,breakerCooldownMs:100},{now:()=>time});await assert.rejects(c.ask('s',q));await assert.rejects(c.ask('s',q));await assert.rejects(c.ask('s',q),e=>e.code==='circuit_open');assert.equal(s.requests.length,2);time=201;healthy=true;await c.ask('s',q);assert.equal(c.failures,0);});
test('Prefix-path proxy accepted without path doubling',async t=>{const s=await fixture(t);await new SystemOneClient({url:s.url+'/proxy/v1/systemone'}).ask('s',q);assert.equal(s.requests[0].url,'/proxy/v1/systemone');});
test('Missing model metadata and empty models list are invalid contracts',async t=>{const s=await fixture(t,({req,res})=>{res.writeHead(200,{'content-type':'application/json'});res.end(req.method==='GET'?'{"models":[]}':'{"answers":{}}');});const c=new SystemOneClient({url:s.url});await assert.rejects(c.ask('s',q),e=>e.code==='invalid_response');await assert.rejects(c.models(),e=>e.code==='invalid_response');});
