import test from 'node:test';import assert from 'node:assert/strict';
import fs from 'node:fs/promises';import path from 'node:path';
import {handleHook} from '../src/hooks.mjs';import {resolveConfig} from '../src/config.mjs';
import {register,compactFunction,functionEndpoint} from '../src/function-hook.mjs';
import {readRegular,atomicJSON,withLock,sessionKey} from '../src/storage.mjs';
import {temp,unverified,verified,history,fakeClient,envelope} from './helpers.mjs';
async function setup(t,messages=unverified()){
 const home=await temp();t.after(()=>fs.rm(home,{recursive:true,force:true}));const transcript=path.join(home,'transcript.jsonl');await fs.writeFile(transcript,messages.map(m=>JSON.stringify(m)).join('\n'));
 const config=resolveConfig({dataDir:path.join(home,'data'),preserveRecentMessages:2,timeoutMs:1000}, {},{readFile:false});const payload={session_id:'test-session',transcript_path:transcript,cwd:home};return {home,config,payload};
}
for(const host of ['claude','codex'])test(`${host} Stop produces host-compatible block then prevents repeats`,async t=>{const {config,payload}=await setup(t);const client=fakeClient();const r=await handleHook('Stop',payload,config,{client,host});assert.equal(r.decision,'block');assert.deepEqual(await handleHook('Stop',payload,config,{client,host}),{});assert.equal(client.calls.length,1);});
test('stop_hook_active true always permits continuation without inference',async t=>{const {config,payload}=await setup(t),client=fakeClient();assert.deepEqual(await handleHook('Stop',{...payload,stop_hook_active:true},config,{client}),{});assert.equal(client.calls.length,0);});
test('Verified transcript automatically runs task gate and does not block',async t=>{const {config,payload}=await setup(t,verified()),client=fakeClient();assert.deepEqual(await handleHook('Stop',payload,config,{client}),{});assert.equal(client.calls.length,1);assert.ok(client.calls[0].questions.correctness);});
test('Stop network/API failure is fail open with sanitized diagnostic',async t=>{const {config,payload}=await setup(t),logs=[];assert.deepEqual(await handleHook('Stop',payload,config,{client:fakeClient(()=>{throw Error('TOP_SECRET')}),log:x=>logs.push(x)}),{});assert.ok(!logs.join().includes('TOP_SECRET'));});
test('Stop shadow records diagnostic but never blocks',async t=>{const {config,payload}=await setup(t);config.shadow=true;assert.deepEqual(await handleHook('Stop',payload,config,{client:fakeClient()}),{});});
test('Parallel Stop calls cannot race past state lock',async t=>{const {config,payload}=await setup(t),client=fakeClient(async(_s,q)=>{await new Promise(r=>setTimeout(r,10));return envelope(q);});const rs=await Promise.all(Array.from({length:5},()=>handleHook('Stop',payload,config,{client})));assert.equal(rs.filter(r=>r.decision==='block').length,1);assert.equal(client.calls.length,1);});
test('Session block cap applies even with new content and elapsed cooldown',async t=>{const {config,payload}=await setup(t);config.maxBlocks=1;await handleHook('Stop',payload,config,{client:fakeClient(),now:()=>100000});const r=await handleHook('Stop',{...payload,last_assistant_message:'Different completion'},config,{client:fakeClient(),now:()=>300000});assert.equal(r.decision,undefined);assert.match(r.systemMessage,/cap has been reached/);});
test('PreCompact saves private checkpoint without modifying host transcript, SessionStart restores once',async t=>{const {config,payload}=await setup(t,history()),before=await fs.readFile(payload.transcript_path,'utf8');assert.deepEqual(await handleHook('PreCompact',payload,config,{client:fakeClient(),host:'codex'}),{});assert.equal(await fs.readFile(payload.transcript_path,'utf8'),before);const r=await handleHook('SessionStart',{...payload,source:'compact'},config,{client:fakeClient(),host:'codex'});assert.equal(r.hookSpecificOutput.hookEventName,'SessionStart');assert.match(r.hookSpecificOutput.additionalContext,/No history was replaced/);assert.ok(!(await handleHook('SessionStart',{...payload,source:'compact'},config,{host:'codex'})).hookSpecificOutput.additionalContext.includes('Historical excerpt'));});
test('Checkpoints do not cross sessions, hosts or working directories',async t=>{const {config,payload}=await setup(t,history());await handleHook('PreCompact',payload,config,{client:fakeClient(),host:'claude'});for(const p of [{...payload,session_id:'other'},{...payload,cwd:'/other'}])assert.ok(!(await handleHook('SessionStart',{...p,source:'compact'},config,{host:'claude'})).hookSpecificOutput.additionalContext.includes('Historical excerpt'));assert.ok(!(await handleHook('SessionStart',{...payload,source:'compact'},config,{host:'codex'})).hookSpecificOutput.additionalContext.includes('Historical excerpt'));});
test('Expired checkpoint not reintroduced',async t=>{const {config,payload}=await setup(t,history());await handleHook('PreCompact',payload,config,{client:fakeClient(),now:()=>1000});assert.ok(!(await handleHook('SessionStart',{...payload,source:'compact'},config,{now:()=>999999999})).hookSpecificOutput.additionalContext.includes('Historical excerpt'));});
test('Malformed/truncated transcript refuses confident hooks',async t=>{const {config,payload}=await setup(t);await fs.appendFile(payload.transcript_path,'\n{oops');const client=fakeClient();assert.deepEqual(await handleHook('Stop',payload,config,{client}),{});assert.equal(client.calls.length,0);});
test('Session IDs cannot escape private directory',()=>{for(const id of ['../../secret','/tmp/a','x\n','☃'])assert.match(sessionKey(id),/^[a-f0-9]{32}$/);});
test('Symlink and directory transcript rejected without reading',async t=>{const home=await temp();t.after(()=>fs.rm(home,{recursive:true,force:true}));await fs.writeFile(path.join(home,'real'),'secret');await fs.symlink(path.join(home,'real'),path.join(home,'link'));await assert.rejects(readRegular(path.join(home,'link'),100));await assert.rejects(readRegular(home,100));});
test('Atomic state has private permissions and exclusive locks',async t=>{const home=await temp();t.after(()=>fs.rm(home,{recursive:true,force:true}));const file=path.join(home,'private','state.json');await atomicJSON(file,{a:1});assert.equal((await fs.stat(file)).mode&0o777,0o600);assert.equal((await fs.stat(path.dirname(file))).mode&0o777,0o700);await withLock(file+'.lock',async()=>assert.rejects(withLock(file+'.lock',async()=>{}),/locked/));});
test('Function hook endpoint matches root /v1 and /v1/systemone',()=>{for(const path of ['', '/v1','/v1/systemone'])assert.equal(functionEndpoint(`http://localhost:8009${path}`),'http://127.0.0.1:8009/v1/systemone');assert.throws(()=>functionEndpoint('https://cloud.example'));});
test('Function adapter uses host $.http response text property, not text()',async()=>{const r=await compactFunction(history(),{preserveRecentMessages:2},async(_u,init)=>{const body=JSON.parse(init.body);return {ok:true,status:200,text:JSON.stringify(envelope(body.questions))};});assert.ok(r.stats.reductionRatio>.5);});
test('Registered function hook replaces history only above reduction floor; failures call next',async()=>{const callbacks={},on=(n,fn)=>callbacks[n]=fn;register(on,{preserveRecentMessages:2});let nexts=0;const next=()=>{nexts++;return 'builtin';},$={env:{get:async()=>undefined},ui:{log:()=>{}},http:{fetch:async(_u,i)=>({ok:true,status:200,text:JSON.stringify(envelope(JSON.parse(i.body).questions))})}};const r=await callbacks['session.compact']($,{messages:history()},next);assert.ok(Array.isArray(r.messages));assert.equal(nexts,0);$.http.fetch=async()=>{throw Error();};assert.equal(await callbacks['session.compact']($,{messages:history()},next),'builtin');assert.equal(nexts,1);});
test('Function auto-compaction triggers at configured percent with reentrancy guard',async()=>{const callbacks={};register((n,f)=>callbacks[n]=f,{compactAtPercent:60});let calls=0,nexts=0;const next=()=>nexts++,$={session:{usage:async()=>({context:{percent:70}}),compact:async()=>{calls++;await callbacks['turn.complete']($,{},next);}},ui:{log:()=>{}}};await callbacks['turn.complete']($,{},next);assert.equal(calls,1);assert.equal(nexts,2);});
