import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';
import {install,uninstall,quoteShell} from '../src/install.mjs';import {BridgeError} from '../src/pure.mjs';
import {temp,ROOT} from './helpers.mjs';
function fakeHost({failTarget,existing=[]}={}){const calls=[],registered=new Set(existing);return {calls,registered,async run(cmd,args){calls.push({cmd,args});if(args[0]==='--version')return {stdout:'fixture 1'};if(args[1]==='get'){if(!registered.has(cmd))throw new BridgeError('not_found','not found');return {};}
 if(args[1]==='add'){if(cmd===failTarget)throw new BridgeError('host_command_failed','test failure');registered.add(cmd);}if(args[1]==='remove')registered.delete(cmd);return {};}};}
async function setup(t){const home=await temp();t.after(()=>fs.rm(home,{recursive:true,force:true}));const env={HOME:home,XDG_CONFIG_HOME:path.join(home,'.config'),XDG_STATE_HOME:path.join(home,'.state')};return {home,env};}
test('Install both hosts with exact CLI arguments and preserve other hooks/settings',async t=>{const {home,env}=await setup(t),host=fakeHost();await fs.mkdir(path.join(home,'.claude'),{recursive:true});const existing={permissions:{deny:['Bash(rm *)']},hooks:{Stop:[{hooks:[{type:'command',command:'echo existing'}]}]}};await fs.writeFile(path.join(home,'.claude','settings.json'),JSON.stringify(existing));const r=await install({env,run:host.run,root:ROOT,overrides:{url:'http://127.0.0.1:9999'}});assert.deepEqual(r.installed,['claude','codex']);const settings=JSON.parse(await fs.readFile(path.join(home,'.claude','settings.json')));assert.deepEqual(settings.permissions,existing.permissions);assert.equal(settings.hooks.Stop.length,2);assert.equal(host.calls.filter(c=>c.args[1]==='add').length,2);assert.ok(host.calls.find(c=>c.cmd==='claude'&&c.args[1]==='add').args.includes('--scope'));assert.ok((await fs.readFile(path.join(home,'.agents','skills','system-one-judgments','SKILL.md'),'utf8')).includes('system_one_verify'));});
test('Repeated installation is idempotent and does not duplicate MCP or hooks',async t=>{const {home,env}=await setup(t),host=fakeHost();await install({env,run:host.run});const r=await install({env,run:host.run});assert.equal(r.already_installed.length,2);assert.equal(host.calls.filter(c=>c.args[1]==='add').length,2);assert.equal(JSON.parse(await fs.readFile(path.join(home,'.codex','hooks.json'))).hooks.Stop.length,1);});
test('Host setup failure rolls back preceding host and restores original bytes',async t=>{const {home,env}=await setup(t),host=fakeHost({failTarget:'codex'});await fs.mkdir(path.join(home,'.claude'));const original='{ "theme": "dark" }\n';await fs.writeFile(path.join(home,'.claude','settings.json'),original);await assert.rejects(install({env,run:host.run}),/failure/);assert.equal(await fs.readFile(path.join(home,'.claude','settings.json'),'utf8'),original);assert.equal(host.registered.size,0);await assert.rejects(fs.stat(path.join(home,'.claude','skills','system-one-belay')),e=>e.code==='ENOENT');});
test('Unowned MCP registration never overwritten',async t=>{const {env}=await setup(t),host=fakeHost({existing:['claude']});await assert.rejects(install({env,run:host.run}),/unowned/);assert.equal(host.calls.filter(c=>c.args[1]==='add').length,0);});
test('Existing skill or malformed settings fails before side effects',async t=>{const {home,env}=await setup(t),host=fakeHost();await fs.mkdir(path.join(home,'.claude','skills','system-one-belay'),{recursive:true});await assert.rejects(install({env,run:host.run,host:'claude'}),/Skill/);assert.equal(host.calls.filter(c=>c.args[1]==='add').length,0);});
test('Uninstall removes only exact owned hooks and preserves shared data/config',async t=>{const {home,env}=await setup(t),host=fakeHost();await install({env,run:host.run});const file=path.join(home,'.codex','hooks.json'),cfg=JSON.parse(await fs.readFile(file));cfg.hooks.Stop[0].hooks.push({type:'command',command:'other-command'});await fs.writeFile(file,JSON.stringify(cfg));const r=await uninstall({env,run:host.run});assert.deepEqual(r.removed,['claude','codex']);assert.equal(JSON.parse(await fs.readFile(file)).hooks.Stop[0].hooks[0].command,'other-command');assert.equal(host.registered.size,0);assert.ok(await fs.stat(path.join(home,'.config','open-jev-bridge','config.json')));});
test('Installer does not persist inherited API credentials',async t=>{const {home,env}=await setup(t),host=fakeHost();env.SYSTEM_ONE_API_KEY='SUPERSECRET';await install({env,run:host.run,host:'claude'});assert.ok(!(await fs.readFile(path.join(home,'.config','open-jev-bridge','config.json'),'utf8')).includes('SUPERSECRET'));});
test('Shell quoting handles spaces, quotes, dollars and semicolons literally',()=>assert.equal(quoteShell("a b'c;$HOME"),"'a b'\\''c;$HOME'"));
test('MCP remove failure is reported rather than falsely confirming uninstall',async t=>{const {env}=await setup(t),host=fakeHost();await install({env,run:host.run,host:'claude'});await assert.rejects(uninstall({env,host:'claude',run:async(c,a)=>{if(a[1]==='remove')throw new BridgeError('host_command_failed','remove failed');return host.run(c,a);}}),/remove failed/);});
test('MCP discovery errors are not mistaken for a missing server',async t=>{const {env}=await setup(t);let adds=0;await assert.rejects(install({env,host:'claude',run:async(_c,a)=>{if(a[1]==='get')throw new BridgeError('host_command_failed','Permission denied');if(a[1]==='add')adds++;return {};}}),/Permission/);assert.equal(adds,0);});
test('Uninstall preserves user-added files inside an installed skill',async t=>{const {home,env}=await setup(t),host=fakeHost();await install({env,run:host.run,host:'claude'});const note=path.join(home,'.claude','skills','system-one-belay','my-notes.md');await fs.writeFile(note,'Keep my work');await uninstall({env,run:host.run,host:'claude'});assert.equal(await fs.readFile(note,'utf8'),'Keep my work');});

test('Generic provider and private API-key-file path persist, but secret contents never do',async t=>{
 const {home,env}=await setup(t),host=fakeHost(),keyfile=path.join(home,'provider.key');await fs.writeFile(keyfile,'private-fixture-token',{mode:0o600});
 const r=await install({env,run:host.run,root:ROOT,overrides:{url:'https://api.typesafe.ai',model:'jev-latest',provider:'jev',allowRemote:true,apiKeyFile:keyfile}});
 const saved=JSON.parse(await fs.readFile(r.config,'utf8'));assert.equal(saved.apiKeyFile,keyfile);assert.equal(saved.provider,'jev');assert.equal(saved.apiKey,undefined);
 assert.ok(!JSON.stringify(host.calls).includes('private-fixture-token'));assert.ok(host.calls.some(x=>x.args.includes('open-jev-bridge')));
 const {resolveConfig}=await import('../src/config.mjs');assert.equal(resolveConfig({},env).apiKey,'private-fixture-token');
});
