import test from 'node:test';import assert from 'node:assert/strict';
import {PassThrough} from 'node:stream';
import {serveMcp} from '../src/mcp.mjs';
import {ToolService} from '../src/tools.mjs';
import {mockSystemOne,mcpProcess,fakeClient,TOOL_INPUTS,command,BIN} from './helpers.mjs';
async function fixture(t,handler,options){const s=await mockSystemOne(handler),m=await mcpProcess(s.url,options);t.after(async()=>{await m.close();await s.close();});return {s,m};}
test('Real stdio process negotiates, lists schemas, and calls typed Kev API',async t=>{const {m,s}=await fixture(t);const list=await m.request('tools/list');assert.equal(list.result.tools.length,14);const r=await m.request('tools/call',{name:'system_one_verify',arguments:TOOL_INPUTS.system_one_verify});assert.equal(r.result.isError,false);assert.equal(r.result.structuredContent.results[0].verdict,'verified');assert.equal(s.requests.length,1);assert.equal(m.stderr,'');});
for(const name of Object.keys(TOOL_INPUTS))test(`MCP end-to-end ${name}`,async t=>{const {m}=await fixture(t);const r=await m.request('tools/call',{name,arguments:TOOL_INPUTS[name]});assert.equal(r.result.isError,false,JSON.stringify(r));const content=JSON.parse(r.result.content[0].text);assert.notEqual(content.status,'invalid_response');});
test('Unknown tool and bad arguments return MCP tool errors not process death',async t=>{const {m}=await fixture(t);for(const [name,args]of [['does_not_exist',{}],['system_one_verify',{claims:['x'],evidence:'y',typo:1}]]){const r=await m.request('tools/call',{name,arguments:args});assert.equal(r.result.isError,true);}assert.deepEqual((await m.request('ping')).result,{});});
test('Unknown methods and invalid RPC produce standard errors',async t=>{const {m}=await fixture(t);assert.equal((await m.request('made_up')).error.code,-32601);assert.equal((await m.request('tools/call',{name:1})).error.code,-32602);m.child.stdin.write('bad-json\n');await new Promise(r=>setTimeout(r,30));assert.ok(m.messages.some(x=>x.error?.code===-32700));});
test('Pre-initialization tools are rejected, unsupported version negotiated explicitly',async()=>{
 const input=new PassThrough(),output=new PassThrough();let text='';output.on('data',s=>text+=s);const run=serveMcp(new ToolService(fakeClient()),{input,output});
 input.write(JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/list'})+'\n');input.write(JSON.stringify({jsonrpc:'2.0',id:2,method:'initialize',params:{protocolVersion:'future-version',capabilities:{},clientInfo:{name:'test',version:'1'}}})+'\n');input.end();await run;const replies=text.trim().split('\n').map(JSON.parse);assert.equal(replies[0].error.code,-32002);assert.equal(replies[1].result.protocolVersion,'2025-11-25');
});
test('UTF8 split across stream chunks remains intact',async()=>{const input=new PassThrough(),output=new PassThrough();let text='';output.on('data',s=>text+=s);const run=serveMcp(new ToolService(fakeClient()),{input,output});const bytes=Buffer.from(JSON.stringify({jsonrpc:'2.0',id:'🙂漢字',method:'ping'})+'\n');for(const b of bytes)input.write(Buffer.from([b]));input.end();await run;assert.equal(JSON.parse(text).id,'🙂漢字');});
test('Oversized lines are discarded and next line still processed',async()=>{const input=new PassThrough(),output=new PassThrough();let text='';output.on('data',s=>text+=s);const run=serveMcp(new ToolService(fakeClient()),{input,output,maxLineBytes:128});input.write('x'.repeat(256));input.write('\n'+JSON.stringify({jsonrpc:'2.0',id:5,method:'ping'})+'\n');input.end();await run;const r=text.trim().split('\n').map(JSON.parse);assert.equal(r[0].error.code,-32600);assert.equal(r[1].id,5);});
test('Cancellation propagates to HTTP and server remains responsive',async t=>{const {m}=await fixture(t,({res})=>{res.writeHead(200,{'content-type':'application/json'});res.write('{');});const id=900; // Send without a request waiter: cancelled calls need not produce a reply.
 m.send({jsonrpc:'2.0',id,method:'tools/call',params:{name:'system_one_query',arguments:TOOL_INPUTS.system_one_query}});await new Promise(r=>setTimeout(r,30));m.send({jsonrpc:'2.0',method:'notifications/cancelled',params:{requestId:id,reason:'test'}});await new Promise(r=>setTimeout(r,30));assert.deepEqual((await m.request('ping')).result,{});assert.ok(!m.messages.some(x=>x.id===id));});
test('CLI malformed hook input exits zero and emits only empty hook object',async()=>{const r=await command([BIN,'hook','--host','codex','--event','Stop'],{input:'not JSON'});assert.equal(r.code,0);assert.deepEqual(JSON.parse(r.stdout),{});});
test('CLI rejects unknown arguments and non-loopback URL without opt-in',async()=>{for(const args of [['serve','--typo'],['doctor','--url','https://example.com']]){const r=await command([BIN,...args]);assert.equal(r.code,1);assert.equal(r.stdout,'');}});
