import fs from 'node:fs/promises';import path from 'node:path';import {execFileSync} from 'node:child_process';import assert from 'node:assert/strict';
import {HOST_EVENTS} from '../src/hooks.mjs';
import {root} from './build-plugins.mjs';import {TOOL_DEFINITIONS} from '../src/tool-schemas.mjs';
const allowed=new Set(['type','properties','required','additionalProperties','items','minItems','maxItems','minProperties','maxProperties','minLength','maxLength','minimum','maximum','enum','const','anyOf','description']);
function schema(s){for(const key of Object.keys(s))assert.ok(allowed.has(key),`Unsupported schema keyword ${key}`);for(const v of Object.values(s.properties??{}))schema(v);if(s.items)schema(s.items);if(typeof s.additionalProperties==='object')schema(s.additionalProperties);for(const v of s.anyOf??[])schema(v);}
for(const t of TOOL_DEFINITIONS){schema(t.inputSchema);assert.equal(t.inputSchema.additionalProperties,false);assert.ok(t.description.length>20);}
assert.equal(new Set(TOOL_DEFINITIONS.map(t=>t.name)).size,14);
async function walk(dir){const files=[];for(const e of await fs.readdir(dir,{withFileTypes:true})){if(['.git','node_modules','coverage','plugins'].includes(e.name))continue;const p=path.join(dir,e.name);if(e.isDirectory())files.push(...await walk(p));else files.push(p);}return files;}
let count=0;for(const file of await walk(root)){if(file.endsWith('.mjs')){execFileSync(process.execPath,['--check',file],{stdio:'pipe'});count++;}if(file.endsWith('.json')&&!file.includes('/reports/'))JSON.parse(await fs.readFile(file,'utf8'));}
async function manifest(base,file){const m=JSON.parse(await fs.readFile(path.join(base,file),'utf8'));assert.match(m.name,/^[a-z][a-z0-9-]*$/);assert.equal(m.version,'0.4.4');for(const value of [m.hooks,m.mcpServers].flat().filter(Boolean)){if(typeof value!=='string')continue;assert.ok(value.startsWith('./')&&!value.includes('..'));await fs.access(path.join(base,value));}return m;}
await manifest(root,'.claude-plugin/plugin.json');await manifest(root,'.codex-plugin/plugin.json');
{
 const base=root;const mcp=JSON.parse(await fs.readFile(path.join(base,'.mcp.json'),'utf8'));assert.equal(mcp.mcpServers['open-jev-bridge'].command,'node');assert.equal(mcp.mcpServers['open-jev-bridge'].args[1],'serve');await fs.access(path.join(base,'bin','open-jev-bridge.mjs'));
 for(const name of ['system-one-judgments','system-one-compaction','system-one-belay']){const text=await fs.readFile(path.join(base,'skills',name,'SKILL.md'),'utf8');assert.ok(text.startsWith('---\nname: '+name+'\n'));assert.match(text,/\ndescription: .+/);}
}
for(const host of ['claude','codex']){const config=JSON.parse(await fs.readFile(path.join(root,'hooks',host+'.json'),'utf8'));assert.deepEqual(Object.keys(config.hooks),HOST_EVENTS[host]);for(const entries of Object.values(config.hooks))for(const group of entries)for(const hook of group.hooks){assert.equal(hook.type,'command');assert.equal(hook.timeout,25);assert.ok(hook.command.includes('${CLAUDE_PLUGIN_ROOT}'));assert.ok(!hook.command.includes('/mnt/data'));}}
for(const file of ['pure.mjs','schema.mjs','providers.mjs','endpoints.mjs','shisa.mjs','shisa-llamacpp.mjs','compact.mjs','function-hook.mjs']){const text=await fs.readFile(path.join(root,'src',file),'utf8');assert.ok(!/from\s+['"]node:|\bprocess\.|\brequire\(/.test(text),`Node dependency in isolated function-hook graph: ${file}`);}
console.log(`PASS: ${count} JavaScript modules parsed; 14 strict tool schemas; Claude/Codex manifests, hooks, skills, portable paths and source plugin integrity validated. Native host validators are separate.`);
